#!/bin/bash
bashrc=~/.bashrc
vimrc=~/.vimrc
tmuxconf=~/.tmux.conf
emacs=~/.emacs
mysnips=~/.vim/mysnips/*

target_directory=~/dotfiles

cp $bashrc $target_directory/bashrc
cp $vimrc $target_directory/vimrc
cp $tmuxconf $target_directory/tmux.conf
cp $emacs $target_directory/emacs
cp $mysnips $target_directory/mysnips
